---
title: "Exam 2016-10-20, emisv463"
author: "Emil K Svensson"
date: "16 October 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(bnlearn)
library(gRain)
```

## a)

```{r}
data <- asia 


# Learned with Hill Climbing algorithm
learned_graph <- hc(asia)

# Aproximated
bayes_net <- bn.fit(learned_graph, data = data)

dist <- cpdist(fitted=bayes_net, nodes=c("A"), 
               evidence=(X == "yes") & (B == "yes"))
cat("The aproximated probability of that person visiting Asia: \n")
prop.table(table(dist))

# Exact (Lautrizen Spiegelhalter)
junction_tree <- compile(as.grain(bayes_net))

cat("The exact probability of that person visiting Asia: \n")
a<- querygrain(junction_tree, nodes=c("A", "X", "B"), type="conditional")


a

```

## b)

```{r}
nographs <- round(29281)

many.graphs <- random.graph(LETTERS[1:5], num = nographs)

moral.graphs <- lapply(many.graphs,moral)
skel.graphs <- lapply(moral.graphs, FUN = skeleton)

mean(skel.graphs %in%  moral.graphs)
```

## c)



## 2

```{r}
states <- paste("z",1:10,sep = "")
symbols <- paste("s",1:11,sep = "")
start <- rep(0.1,10)

#Just to see the structure
#initHMM(states, symbols)

# The transition probabilities, since we only can move 
trans <- matrix(0,ncol = 10, nrow = 10)
diag(trans) <- 0.5
diag(trans[,-1]) <- 0.5
trans[10,1] <- 0.5
#trans[1,10] <- 0.5

# Making sure the probabilities sum to 1 in each row
#apply(trans, MARGIN = 1, FUN = sum)

emission <- matrix(0,ncol = 11, nrow = 10)
diag(emission) <- 0.5

# The Emission probabilities are our uncertaintiec in the position of the robot.

# Brute force set up, Nick, Rasmus and Sascha probably has a nicer ways of solving this 
diag(emission) <- 0.1
diag(emission[,-1]) <- 0.1 
diag(emission[-1,]) <- 0.1 
diag(emission[c(-1:-2),]) <- 0.1
diag(emission[,c(-1:-2)]) <- 0.1 
emission[10,2] <- 0.1
emission[2,10] <- 0.1
emission[2,10] <- 0.1
emission[1,10] <- 0.1
emission[9:10,1] <- 0.1
emission[1,9] <- 0.1


emission[,11] <- rep(0.5, times = 10)
#trans[,11] <- rep(0,10)

emission
trans
```

```{r}
robot <- initHMM(states,symbols,start,trans,emission)
```

```{r}


new_em <- diag(0, nrow = 5, ncol = 10 )
#diag(new_em[,-1]) <- rep(0.5, 4)
#new_em[5,1] <- 0.5


new_em[,c(1)]<- c(0.5,0,0,0,0.5)
new_em[,c(2)]<- c(0.5,0.5,0,0,0)
new_em[,c(3)]<- c(0,0.5,0.5,0,0)
new_em[,c(4)]<- c(0,0,0.5,0.5,0)
new_em[,c(5)]<- c(0,0,0,0.5,0.5)

new_em <- new_em[c(1,1,2,2,3,3,4,4,5,5),c(1,1,2,2,3,3,4,4,5,5)]

new_em
colnames(new_em) <- paste0("x",c(1,1,2,2,3,3,4,4,5,5))
rownames(new_em) <- paste0("z",c(1,1,2,2,3,3,4,4,5,5))

new_trans <- diag(0,ncol = 5, nrow = 5)
new_trans

new_trans[1,c(5,1,2)] <- c(0.333,0.3333,0.3333)
new_trans[2,c(1,2,3)] <- c(0.333,0.3333,0.3333)
new_trans[3,c(2,3,4)] <- c(0.333,0.3333,0.3333)
new_trans[4,c(3,4,5)] <- c(0.333,0.3333,0.3333)
new_trans[5,c(4,5,1)] <- c(0.333,0.3333,0.3333)
new_trans

new_trans <- new_trans[c(1,1,2,2,3,3,4,4,5,5),c(1,1,2,2,3,3,4,4,5,5)]

colnames(new_trans) <- paste0("z",c(1,1,2,2,3,3,4,4,5,5))
rownames(new_trans) <- paste0("z",c(1,1,2,2,3,3,4,4,5,5))
new_trans
```

```{r}

hidden_states <- paste0("z",rep(1:5,each=2))
observed_states <- paste0("x",rep(1:5, each = 2))

robot <- initHMM(hidden_states,observed_states,start,new_trans,new_em)

```


```{r}

```

